// This file is autogenerated. Changes will be overwritten.
#include "7GIMN6H6VK/moc_qjoystick.cpp"
#include "EWIEGA46WW/moc_genericmonitor.cpp"
#include "EWIEGA46WW/moc_genericworker.cpp"
#include "EWIEGA46WW/moc_specificmonitor.cpp"
#include "EWIEGA46WW/moc_specificworker.cpp"
